### ISSUE TITLE
Install to Laravel !?

### ISSUE THREAD

**Issue by odera89** [chickenTikkaMasala/GPIO#2]
How I can install into laravel? via NPM or Composer?

**Comment by bashleigh** [comment]
I just realised, I never actually added this to packagist; I will do that now.

If you're desperate, you can install via composer using the repositories key in composer.json. 

```
    "repositories": [
            {
                "url": "https://github.com/chickenTikkaMasala/GPIO",
                "type": "vcs"
            }
        ]
```

Like this https://github.com/bashleigh/raspberry-pi-example/blob/master/composer.json#L32

I'll add this to packagist now and let you know when it's resolved.

**Comment by bashleigh** [comment]
Ok, I've updated the read me with new instructions and made a release for v1.0 which is now on packagist so you can use composer to install this repository. `composer require chickentikkamasala/gpio` or within the json like `"chickentikkamasala/gpio": "1.0"`
